# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Thoughts from Brent
email: brentseidel@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  This is an irregularly updated blog.  Mostly, it will cover technology related items of
  interest to me, but might occasionally have some other content.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://brentseidel.github.io" # the base hostname & protocol for your site
github_username:  BrentSeidel
exclude: ['Rakefile']

# Build settings
markdown: kramdown
